language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.2.3
  - jruby-1.7.4
  - jruby-1.7.23
jdk:
  - openjdk7 # for jruby
before_script: export JRUBY_OPTS="--server -Xcompile.invokedynamic=false -J-Xss1024k -J-Xmx652m -J-XX:+UseConcMarkSweepGC"
matrix:
  allow_failures:
    #- rvm: jruby-1.7.4
env: ARUBA_TIMEOUT=120 RAILS_ENV=development AHN_ENV=development
#notifications:
#  irc: "irc.freenode.org#adhearsion"
